---
version: 3
includes:
  init:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/backstage/init.yaml
  git:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/git/git.yaml
  docker:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/docker/build.yaml
  trivy:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/docker/scan.yaml
  image:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/docker/copy.yaml

dotenv: ['.env', '{{.HOME}}/.env']

vars:
  PROJECT_NAME:
    sh: echo ${PWD##*/}
  DOCKERFILE: "packages/backend/Dockerfile"
  DEV_IMAGE_TAG:
    sh: date +"%y%m%d.%H%M"
  DEV_IMAGE_REGISTRY: ttl.sh
  DEV_IMAGE_NAME:
    sh: echo "sthings-backstage-$(openssl rand -hex 6)"
  DAGGER_MODULE: github.com/stuttgart-things/dagger/docker

tasks:
  build-backend:
    desc: Build backstage backend bundle
    cmds:
      - yarn install --immutable
      - yarn tsc
      - yarn build:backend

  build-push-scan-image:
    desc: Build, scan and push image to ghcr
    deps:
      - build-backend
    vars:
      SOURCE_IMAGE: "{{ .DEV_IMAGE_REGISTRY }}/{{ .DEV_IMAGE_NAME }}:{{ .DEV_IMAGE_TAG }}"
      PROJECT: "{{ .PROJECT_NAME }}"
      VERSION: "{{ .DEV_IMAGE_TAG }}"
    cmds:
      - |
        dagger call -m github.com/stuttgart-things/blueprints/kubernetes-microservice@v1.62.0 \
          bake-and-scan-image \
          --src . \
          --repository-name "{{ .DEV_IMAGE_NAME }}" \
          --registry-url "{{ .DEV_IMAGE_REGISTRY }}" \
          --tag "{{ .DEV_IMAGE_TAG }}" \
          --dockerfile "{{ .DOCKERFILE }}" \
          --progress plain \
          export --path=/tmp/trivy-scan-{{ .PROJECT_NAME }}.json

        echo ""
        echo "✅ Build, push, and scan complete!"
        echo "📄 Report: /tmp/trivy-scan-{{ .PROJECT_NAME }}.json"

        if command -v jq &> /dev/null; then
          echo ""
          echo "📊 Vulnerability Summary:"
          jq -r '.Results[]? | select(.Vulnerabilities) | "\(.Target): \(.Vulnerabilities | length) vulnerabilities"' \
            /tmp/trivy-scan-{{ .PROJECT_NAME }}.json 2>/dev/null || echo "✅ No vulnerabilities found!"
        fi
      - gum confirm "Push {{ .SOURCE_IMAGE }} to ghcr.io/stuttgart-things/{{ .PROJECT }}:{{ .VERSION }}?"
      - task: image:copy-image
        vars:
          SOURCE: "{{ .SOURCE_IMAGE }}"
          TARGET: ghcr.io/stuttgart-things/{{ .PROJECT }}:{{ .VERSION }}
          TARGET_USERNAME: $GITHUB_USER
          TARGET_PASSWORD: env:GITHUB_TOKEN # pragma: allowlist secret

  dev:
    desc: Start Backstage in development mode with .env loaded
    cmds:
      - |
        bash -c '
        set -a
        source .env
        set +a
        echo "Environment variables loaded:"
        echo "GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID:0:10}..."
        echo "GITHUB_CLIENT_SECRET is set"
        echo "GITHUB_TOKEN is set"
        echo "BACKEND_SECRET is set"
        yarn start
        '

  do:
    desc: Select a task to run
    cmds:
      - |
        # Extract task names (keep internal colons, remove trailing colon)
        task_name=$(task -l | awk '/^\*/ {print $2}' | \
          sed 's/:$//' | gum choose)

        # Run the selected task
        [ -n "$task_name" ] && task "$task_name"

  default:
    desc: Default task is select & do (work)
    cmds:
      - task do
