---
version: 3
includes:
  init:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/backstage/init.yaml
  git:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/git/git.yaml
  docker:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/docker/build.yaml

dotenv: ['.env', '{{.HOME}}/.env']

vars:
  PROJECT_NAME:
    sh: echo ${PWD##*/}
  DOCKERFILE: "packages/backend/Dockerfile"
  DEV_IMAGE_TAG:
    sh: date +"%y.%m%d.%H%M"
  DEV_IMAGE_REGISTRY: ttl.sh
  DEV_IMAGE_REPOSITORY: stuttgart-things


tasks:
  image-build:
    desc: Build image
    cmds:
      - task: docker:image-build
        vars:
          REGISTRY_URL: "{{ .DEV_IMAGE_REGISTRY }}"
          IMAGE_REPOSITORY: "{{ .DEV_IMAGE_REPOSITORY }}"
          IMAGE_NAME: "{{ .PROJECT_NAME }}"
          PATH_TO_DOCKERFILE: "{{ .DOCKERFILE }}"
          TAG: "{{ .DEV_IMAGE_TAG }}"

  dev:
    desc: Start Backstage in development mode with .env loaded
    cmds:
      - |
        bash -c '
        set -a
        source .env
        set +a
        echo "Environment variables loaded:"
        echo "GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID:0:10}..."
        echo "GITHUB_CLIENT_SECRET is set"
        echo "GITHUB_TOKEN is set"
        echo "BACKEND_SECRET is set"
        yarn start
        '

  do:
    desc: Select a task to run
    cmds:
      - |
        # Extract task names (keep internal colons, remove trailing colon)
        task_name=$(task -l | awk '/^\*/ {print $2}' | \
          sed 's/:$//' | gum choose)

        # Run the selected task
        [ -n "$task_name" ] && task "$task_name"

  default:
    desc: Default task is select & do (work)
    cmds:
      - task do
